export default [
  {
    component: () => import("./Cart.vue"),
    name: "cart",
    path: "cart",
    meta: {},
    beforeEnter: undefined,
  },
  {
    component: () => import("./Explore.vue"),
    name: "explore",
    path: "explore",
    meta: {},
    beforeEnter: undefined,
  },
  {
    component: () => import("./Home.vue"),
    name: "home",
    path: "home",
    meta: {},
    beforeEnter: undefined,
  },
  {
    component: () => import("./Profile.vue"),
    name: "profile",
    path: "profile",
    meta: {},
    beforeEnter: undefined,
  },
  {
    component: () => import("./Shop.vue"),
    name: "shop",
    path: "shop",
    meta: {},
    beforeEnter: undefined,
  },
  {
    component: () => import("./Splash.vue"),
    name: "splash",
    path: "splash",
    meta: {},
    beforeEnter: undefined,
  },
  {
    component: () => import("./Wishlist.vue"),
    name: "wishlist",
    path: "wishlist",
    meta: {},
    beforeEnter: undefined,
  },
  {
    path: "/auth",
    children: [
      {
        component: () => import("./auth/OnBoardOne.vue"),
        name: "onboardone",
        path: "onboardone",
        meta: {},
        beforeEnter: undefined,
      },
      {
        component: () => import("./auth/SignIn.vue"),
        name: "signin",
        path: "signin",
        meta: {},
        beforeEnter: undefined,
      },
      {
        component: () => import("./auth/SignUp.vue"),
        name: "signup",
        path: "signup",
        meta: {},
        beforeEnter: undefined,
      },
    ],
  },
];
